#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage:  <called from Event-Driven Ansible>
#
#      This playbook processes and filters events from Kafka  . . .
#
- name: Filter Events from Kafka
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # input: '{{ ansible_eda.event.payload }}'
    authtoken: "{{ lookup('ansible.builtin.env', 'AUTHTOKEN') }}"
    server: "ec2-54-144-142-30.compute-1.amazonaws.com"
    container_id: 3
  tasks:
    - name: Create Artifact using existing container
      netcraftsmen.kafka.soar_event:
        server: '{{ server }}'
        authtoken: '{{ authtoken }}'
        container_id: '{{ container_id }}'
        artifact:
          name: "cfic_demo_artifact"
          # source_data_identifier: "IR_3458575"
          tags: ['spouse_and_child']
          type: "network"
          label: "mac_event"
        cef:
          deviceMacAddress: “00:0D:60:AF:1B:61”
        metadata:
          msg: the quick brown fox jumped over the lazy dog