#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage:  <called from Event-Driven Ansible>
#
#      This playbook processes Kafka events from Event-Driven Ansible, creating artifacts
#      in the Splunk SOAR platform
#
- name: Create an artifacts in Splunk SOAR
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    authtoken: "{{ lookup('ansible.builtin.env', 'SOAR_AUTHTOKEN') }}"
    server: "{{ lookup('ansible.builtin.env', 'SOAR_SERVER') }}"
    # extra_vars
    networkName: 'UNKNOWN'
    bar: 'foo'

  tasks:
    - name:
      ansible.builtin.debug:
        msg:
         - '{{ bar }} {{ networkName }}'
           # - '{{ ansible_eda.event }}'

    - name: Create Container
      netcraftsmen.kafka.soar_event:
        server: '{{ server }}'
        authtoken: '{{ authtoken }}'
        container:
          name: "cfic_demo" 
          description: "A brief useful description of the behavior tracked by this container"
          label: events
          sensitivity: red
          severity: medium
          tags: ['unauthorized_mac']
      register: result

    - name: Create Artifacts
      netcraftsmen.kafka.soar_event:
        server: '{{ server }}'
        authtoken: '{{ authtoken }}'
        container_id: '{{ result.containter_id }}'
        artifact:
          name: "cfic_demo_artifact"
          source_data_identifier: '{{ ansible_eda.event.networkName }}'
          tags: ['spouse_and_child']
          type: "network"
          label: "mac_event"
        cef:
          deviceMacAddress: “00:0D:60:AF:1B:61”
          sourceUserId: "robert@example.net"
          message: "Event-Driven Ansible"
        metadata: {}