#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage:  <called from Event-Driven Ansible>
#
#      This playbook processes Kafka events from Event-Driven Ansible, creating artifacts
#      in the Splunk SOAR platform
#
- name: Create an artifacts in Splunk SOAR
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    authtoken: "{{ lookup('ansible.builtin.env', 'SOAR_AUTHTOKEN') }}"
    server: "{{ lookup('ansible.builtin.env', 'SOAR_SERVER') }}"
    # extra_vars
    networkName: foo
    container_id: 0  # If container_id is passed as an extra_var, use the container specified.

  tasks:
    - name:
      ansible.builtin.debug:
        msg:
         - '{{ networkName }}'
           # - '{{ ansible_eda.event }}'

    - name: Create Container
      netcraftsmen.kafka.soar_event:
        server: '{{ server }}'
        authtoken: '{{ authtoken }}'
        container:
          name: '{{ ansible_eda.event.networkName }}'
          description: "{{ ansible_eda.event.network }}"
          label: events
          sensitivity: red
          severity: medium
          tags: ['network_clients']
      register: result
      when: container_id == 0 

    - name: Create Artifacts
      netcraftsmen.kafka.soar_event:
        server: '{{ server }}'
        authtoken: '{{ authtoken }}'
        container_id: '{{ result.container_id | default(container_id) }}'
        artifact:
          name: '{{ item.id }}'
          description: '{{ item.description }}'
          source_data_identifier: '{{ item.id }}'
          tags: ['{{ item.status }}', '{{ item.recentDeviceConnection }}']
          type: "network"
          label: "network_clients"
        cef:
          deviceMacAddress: “{{ item.mac }}”
          deviceAddress: "{{ item.ip }}"
          sourceUserId: "{{ item.user }}"
          c6a1: "{{ item.ip6Local }}"
          c6a1Label: 'IPv6Local'
          DeviceVendor: '{{ item.manufacturer }}'
          message: "{{ item.description | default(omit) }}"
        metadata: {}
      loop: '{{ ansible_eda.event.payload }}'