#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage: ansible-rulebook --rulebook rb.kafka.yml -i inventory.yml  -vvv
#
- name: Kafka consumer for Meraki clients
  hosts: all

  sources:
   - netcraftsmen.kafka.consumer:
       host: pkc-n00kk.us-east-1.aws.confluent.cloud
       port: 9092
       # cafile:    The optional certificate authority file path containing certificates
       # certfile:  The optional client certificate file path containing the client
       # keyfile:   The optional client key file path containing the client private key
       # password:  The optional password to be used when loading the certificate chain
       check_hostname: False
       encoding: utf-8
       topic: cfic_0
       group_id: group_1
       offset: latest

  rules:
   - name: Filter MAC address
     condition: event.payload.message == "Ansible is super cool!"

  action:
    run_playbook:
      name: pb.soar_artifact.yml