#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage: 
#             export ANSIBLE_CONFIG=/root/cfic/cfic/playbooks/ansible.cfg
#             ansible-rulebook -r rb.kafka.yml -i inventory.yml -v --env-vars CLUSTER_API_KEY,CLUSTER_API_SECRET,TOPIC,OFFSET,GROUP,CLUSTER_HOST,CLUSTER_PORT
- name: Kafka consumer for Meraki clients publisked in Kafka
  hosts: all

  sources:
   - netcraftsmen.kafka.consumer:
        host: "{{ CLUSTER_HOST }}"          # pkc-n00kk.us-east-1.aws.confluent.cloud
        port: "{{ CLUSTER_PORT }}"          # 9092  
        username: "{{ CLUSTER_API_KEY }}"
        password: "{{ CLUSTER_API_SECRET }}"
        check_hostname: False
        encoding: utf-8
        topic: "{{ TOPIC }}"                # cfic_0
        group_id: "{{ GROUP }}"             # semaphore_1
        offset: "{{ OFFSET }}"              # latest

  rules:
    - name: match on everything
      condition: event.payload is defined
      action:
        run_playbook:     
          name: pb.soar.yml
          delay: 1                          # optional, in seconds
          extra_vars:
            networkName: BAR
            container_id: 0                 # 0 = create new container
          verbosity: 1
