#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage: ansible-rulebook --rulebook rb.kafka.yml -i inventory.yml  -v
#
- name: Kafka consumer for Meraki clients
  hosts: all

  sources:
   - netcraftsmen.kafka.consumer:
   # consumer is in the current directory for now
   # - consumer:
        host: pkc-n00kk.us-east-1.aws.confluent.cloud
        port: 9092
        username: # CLUSTER_API_KEY
        password: # CLUSTER_API_SECRET
        check_hostname: False
        encoding: utf-8
        topic: cfic_0
        group_id: semaphore_1
        offset: latest

  rules:
    - name: match on anything
      condition:  event.payload is defined
      action:
        debug:
          var:  event.payload

        # run_playbook:
          # name: pb.soar_artifact.yml