#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage: ansible-rulebook --rulebook rb.kafka.yml -i inventory.yml  -v
#             ansible-rulebook -r rb.kafka.yml -i inventory.yml -v --env-vars CLUSTER_API_KEY,CLUSTER_API_SECRET,TOPIC,GROUP,CLUSTER_HOST,CLUSTER_PORT
#
- name: Kafka consumer for Meraki clients publisked in Kafka
  hosts: all

  sources:
   - netcraftsmen.kafka.consumer:
        host: "{{ CLUSTER_HOST }}"          # pkc-n00kk.us-east-1.aws.confluent.cloud
        port: "{{ CLUSTER_PORT }}"          # 9092  
        username: "{{ CLUSTER_API_KEY }}"
        password: "{{ CLUSTER_API_SECRET }}"
        check_hostname: False
        encoding: utf-8
        topic: "{{ TOPIC }}"                # cfic_0
        group_id: "{{ GROUP }}"             # semaphore_1
        offset: "{{ OFFSET }}"              # latest

  rules:
    - name: match on everything for now
      condition:  
        any:
          - event.payload is defined
          - event.networkName == "SWISSWOOD"
      action:
        run_playbook:     
          name: pb.soar.yml
          delay: 1                          # optional, in seconds
          extra_vars: 
          verbosity: 1

    - name: example of matching on a specific value(s)
      condition:
        all:
          - event.networkName == "SWISSWOOD"
          - event.network == "L_629378047925028460"
      action:
        debug:
          var: event.payload