#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      Author: @joelwking
#
#      Usage: 
#             export ANSIBLE_CONFIG=/root/cfic/cfic/playbooks/ansible.cfg
#             ansible-rulebook -r rb.pretty.yml -i inventory.yml -v --env-vars CLUSTER_API_KEY,CLUSTER_API_SECRET,TOPIC,GROUP,OFFSET,CLUSTER_HOST,CLUSTER_PORT
- name: Kafka consumer, pretty print the event (for debugging)
  hosts: all

  sources:
   - netcraftsmen.kafka.consumer:
        host: "{{ CLUSTER_HOST }}"          # pkc-n00kk.us-east-1.aws.confluent.cloud
        port: "{{ CLUSTER_PORT }}"          # 9092  
        username: "{{ CLUSTER_API_KEY }}"
        password: "{{ CLUSTER_API_SECRET }}"
        check_hostname: False
        encoding: utf-8
        topic: "{{ TOPIC }}"                # cfic_0
        group_id: "{{ GROUP }}"             # semaphore_1
        offset: "{{ OFFSET }}"              # latest

  rules:
    - name: Example of visualizing the data from Kafka
      enabled: true                         # enabled for testing
      condition: event.payload is defined
      actions:
        - print_event:
            pretty: true
